[files]
extend-exclude = [
    "scripts/", # Scripts can easily contain false positives
    ".git/",
    "*.svg",
    "TESTVECTORS",
    "*.lean" # Allow in lean anything since identifies are often false positives
]

[default]
extend-ignore-re = [
    # Patterns which appear to be 36 or more characters of Base64/Base64url
    '\b[0-9A-Za-z+/]{36,}\b',
    '\b[0-9A-Za-z_-]{36,}\b',
]

[default.extend-words]
"AKE" = "AKE" # Authenticated Key Exchange
"Ono" = "Ono" # Surname
"Tung" = "Tung" # Name
"Monts" = "Monts" # Abbreviation for Montgomery
"thm" = "thm" # Abbreviation for theorem
