name = "Curve25519Dalek"
version = "0.1.0"
keywords = ["formal verification"]
defaultTargets = ["Curve25519Dalek"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3
weak.linter.style.longLine = false
maxRecDepth = 10000

[[require]]
name = "aeneas"
git = "https://github.com/AeneasVerif/aeneas.git"
subDir = "backends/lean"
rev = "main"

[[require]]
name = "Canonical"
git = "https://github.com/chasenorman/CanonicalLean"
rev = "v4.25.0"

[[lean_lib]]
name = "Curve25519Dalek"
