name = "Curve25519Dalek"
version = "0.1.0"
keywords = ["formal verification"]
defaultTargets = ["Curve25519Dalek"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3
weak.linter.style.longLine = false
maxRecDepth = 10000

[[require]]
name = "aeneas"
git = "https://github.com/AeneasVerif/aeneas.git"
subDir = "backends/lean"
rev = "0118abaf3343f0326784b508392c93ad793b8146"

[[require]]
name = "PrimeCert"
git = "https://github.com/kckennylau/PrimeCert.git"
rev = "3df9b66"

[[lean_lib]]
name = "Curve25519Dalek"

[[lean_lib]]
name = "Utils"

[[lean_exe]]
name = "deps"
root = "Utils.Deps"
supportInterpreter = true

[[lean_exe]]
name = "listfuns"
root = "Utils.ListFunsMain"
supportInterpreter = true

[[lean_exe]]
name = "syncstatus"
root = "Utils.SyncStatus"
supportInterpreter = true
